### ISSUE TITLE
Client freeze when changing tabs

### ISSUE THREAD

**Issue by res7702** [ovflowd/chocolatey#356]
Sometimes when you change away from the client, after you come back your client is frozen, its not actually frozen. I don't know if this happens on every browser but its focused on the buttons top left. To "unfreeze" the flash part you need to put your cursor on the buttons top left. Maybe the implementation is wrong and it shouldn't focus on those buttons but the flash element. I don't really know a lot about PHP, but this is what I assume is happening, also as much as I'm aware this doesn't happen on Habbo.

**Comment by ovflowd** [comment]
Yes I will give a check. I remember Habbo added an "unfreeze" button. Will add it.

Thanks :)
