### ISSUE TITLE
php artisan migrate Error

### ISSUE THREAD

**Issue by iPrinz96** [ovflowd/chocolatey#357]
`PHP Warning:  require_once(/var/www/html/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/html/bootstrap/app.php on line 4
PHP Fatal error:  require_once(): Failed opening required '/var/www/html/bootstrap/../vendor/autoload.php' (include_path='.:/usr/share/php') in /var/www/html/bootstrap/app.php on line 4
`

Edit: if i go on my Website come this: 
Warning. Please read Chocolatey Installation Tutorial. You need configure your servers DocumentRoot to the public folder of this CMS. Thanks!

**Comment by TheOmanNorge** [comment]
Are you hosting the webserver on Windows or Linux? 

> If you're using Linux, change from "/var/www/html/" to "/var/www/html/public".

> If you're using IIS, from "C:/inetpub/wwwroot/" to "C:/inetpub/wwwroot/public".

Did you download from Binaries?
Binaries has the vendor files if you are missing them, if you already have, then ignore this step.

**Comment by iPrinz96** [comment]
Yes. I think brinaries.

Also cd /var/www/html/public and than  php artisan migrate?

**Comment by iPrinz96** [comment]
Ah. Fixxed.
Download:  Binaries

But Website say: 
Warning. Please read Chocolatey Installation Tutorial. You need configure your servers DocumentRoot to the public folder of this CMS. Thanks!

**Comment by iPrinz96** [comment]
Help?...

**Comment by ovflowd** [comment]
You need change your DocumentRoot to public/ folder.

@TheOmanNorge may help you.

**Comment by iPrinz96** [comment]
And how i do that?

**Comment by iPrinz96** [comment]
I think i know how.
I test it after

**Comment by iPrinz96** [comment]
Solution:
cd /etc/apache2/sites-available/ 
nano 000-default.conf
And Change from "/var/www/html/" to "/var/www/html/public".
After that: service apache2 restart

**Comment by ovflowd** [comment]
Exactly @iPrinz96 that was what I said 😄 

Can I close this issue?
