### ISSUE TITLE
loginstep?

### ISSUE THREAD

**Issue by lifelies** [ovflowd/chocolatey#358]
When I try to enter my hotel, the last thing I see in control = http://xxx/api/log/loginstep (http://prntscr.com/h8rfzr)

On that page I get to see this: http://prntscr.com/h8rg94

Is it my SWF or is it the CMS? Because I can't seem to find anything wrong with my SWF.

**Comment by lifelies** [comment]
Oh and at 76% I get disconnected

**Comment by ovflowd** [comment]
Isnt Chocolatey. 99% probably that it's your SWF or SWF configuration or Emulator configuration.

Loginstep isn't an error.

**Comment by ovflowd** [comment]
The error that appears when you access loginstep it's because only the SWF can access it obviously. If you try to access it by the browser it will throw an exception.

Please read more carefully the documentation before creating issues without ever knowing what is happening.

**Comment by ovflowd** [comment]
Closing since seems that Author abandoned the Issue.

**Comment by lifelies** [comment]
Oh, hi. Didn't got an email, so didnt knew the issue was answered. 

Anyhow, there seem to be nothing wrong with the SWF. Someone checked them for me on his own hotel and he told me to send the lumen log thingie, because we don't really know what's wrong with it. It says arcturus @ localhost, but the .env is filled in correctly with root etc, so maybe it;s nothing, but maybe it solves my problem and also I had opened notepad++ and everytime I entered the client (and got dc on 76%) this log was created

`[2017-11-15 13:08:15] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) in C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php:67
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(67): PDO->__construct('mysql:host=loca...', 'arcturus', 'arcturus', Array)
#1 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'arcturus', 'arcturus', Array)
#2 C:\xampp\htdocs\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 C:\xampp\htdocs\vendor\illuminate\database\Connectors\ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(915): call_user_func(Object(Closure))
#6 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(940): Illuminate\Database\Connection->getPdo()
#7 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#8 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#9 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#10 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#11 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#12 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1705): Illuminate\Database\Connection->select('select * from `...', Array, true)
#13 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#14 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(479): Illuminate\Database\Query\Builder->get(Array)
#15 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(463): Illuminate\Database\Eloquent\Builder->getModels(Array)
#16 C:\xampp\htdocs\vendor\illuminate\database\Concerns\BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#17 C:\xampp\htdocs\app\Models\User.php(162): Illuminate\Database\Eloquent\Builder->first()
#18 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(438): App\Models\User->getIsBannedAttribute(NULL)
#19 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('isBanned', NULL)
#20 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('isBanned')
#21 C:\xampp\htdocs\vendor\sofa\hookable\src\Hookable.php(90): Illuminate\Database\Eloquent\Model->getAttribute('isBanned')
#22 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1321): App\Models\User->getAttribute('isBanned')
#23 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(41): Illuminate\Database\Eloquent\Model->__get('isBanned')
#24 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#41 C:\xampp\htdocs\public\index.php(28): Laravel\Lumen\Application->run()
#42 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) (SQL: select * from `bans` where `user_id` = 2 limit 1) in C:\xampp\htdocs\vendor\illuminate\database\Connection.php:664
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1705): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(479): Illuminate\Database\Query\Builder->get(Array)
#5 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(463): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 C:\xampp\htdocs\vendor\illuminate\database\Concerns\BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#7 C:\xampp\htdocs\app\Models\User.php(162): Illuminate\Database\Eloquent\Builder->first()
#8 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(438): App\Models\User->getIsBannedAttribute(NULL)
#9 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('isBanned', NULL)
#10 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('isBanned')
#11 C:\xampp\htdocs\vendor\sofa\hookable\src\Hookable.php(90): Illuminate\Database\Eloquent\Model->getAttribute('isBanned')
#12 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1321): App\Models\User->getAttribute('isBanned')
#13 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(41): Illuminate\Database\Eloquent\Model->__get('isBanned')
#14 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#21 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#31 C:\xampp\htdocs\public\index.php(28): Laravel\Lumen\Application->run()
#32 {main}  
`
