### ISSUE TITLE
Blank Client Site

### ISSUE THREAD

**Issue by iPrinz96** [ovflowd/chocolatey#359]
Hello.
See Site: https://picr.ws/i/GXJ
This error was coming after the Chocolatey Update.

Link: vip.HabbOriginal.de

**Comment by ovflowd** [comment]
You just need to configure correctly the SWF links.

**Comment by ovflowd** [comment]
Make sure everything is rgith. See the console and network tab from Chrome.

**Comment by iPrinz96** [comment]
I dont have Change anythink after this update.
Bevor it, ist work.
```
`'game' => [
        'gordon'   => 'http://vip.habboriginal.de/public/swf/gordon/PRODUCTION-201611291003-338511768/',
        'flash'    => 'http://vip.habboriginal.de/public/swf/gordon/PRODUCTION-201611291003-338511768/Habbo.swf',
        'gamedata' => [
            'figuredata'        => 'http://vip.habboriginal.de/public/swf/gamedata/figuredata.xml',
            'furnidata'         => 'http://vip.habboriginal.de/public/swf/gamedata/furnidata.xml',
            'productdata'       => 'http://vip.habboriginal.de/public/swf/gamedata/productdata.txt',
            'variables'         => 'http://vip.habboriginal.de/public/swf/gamedata/external_variables.txt',
            'texts'             => 'http://vip.habboriginal.de/public/swf/gamedata/external_flash_texts.txt',
            'overrideVariables' => 'http://vip.habboriginal.de/public/swf/gamedata/override/external_override_variables.txt',
            'overrideTexts'     => 'http://vip.habboriginal.de/public/swf/gamedata/override/external_flash_override_texts.txt',

```

**Comment by ovflowd** [comment]
You really don't read what I say, right?

I said that you NEED to change the URL. Because Chocolatey changed how works.

A tip, just removed the "public" from your URI's.

**Comment by ovflowd** [comment]
Just another tip, if you see what you did when your changed the DocumentRoot folder, you will understand that the base directory now it's the public folder. Because of that, no needing of add public on the URL.

:eyes: 😃

**Comment by sant0ro** [comment]
Just another tip, if you see what you did when your changed the DocumentRoot folder, you will understand that the base directory now it's the public folder. Because of that, no needing of add public on the URL.

:eyes: 😃

**Comment by iPrinz96** [comment]
Aaaah. Okay😂 Iam stupid. Omg😂😂😂
