### ISSUE TITLE
Register conflict - Error 409

### ISSUE THREAD

**Issue by OliverFIN** [ovflowd/chocolatey#360]
![image](https://user-images.githubusercontent.com/33379947/32795134-18a6ae74-c96b-11e7-8b6e-b154193d9f82.png)
Provides an error 409 in console.

`[2017-11-08 13:35:03] lumen.ERROR: PDOException: SQLSTATE[23000]: Integrity constraint violation: 1062 Duplicate entry '0' for key 'PRIMARY' in C:\inetpub\wwwroot\vendor\illuminate\database\Connection.php:449
Stack trace:
#0 C:\inetpub\wwwroot\vendor\illuminate\database\Connection.php(449): PDOStatement->execute()
#1 C:\inetpub\wwwroot\vendor\illuminate\database\Connection.php(640): Illuminate\Database\Connection->Illuminate\Database\{closure}('insert into `ch...', Array)
#2 C:\inetpub\wwwroot\vendor\illuminate\database\Connection.php(607): Illuminate\Database\Connection->runQueryCallback('insert into `ch...', Array, Object(Closure))
#3 C:\inetpub\wwwroot\vendor\illuminate\database\Connection.php(450): Illuminate\Database\Connection->run('insert into `ch...', Array, Object(Closure))
#4 C:\inetpub\wwwroot\vendor\illuminate\database\Connection.php(404): Illuminate\Database\Connection->statement('insert into `ch...', Array)
#5 C:\inetpub\wwwroot\vendor\illuminate\database\Query\Processors\Processor.php(32): Illuminate\Database\Connection->insert('insert into `ch...', Array)
#6 C:\inetpub\wwwroot\vendor\illuminate\database\Query\Builder.php(2138): Illuminate\Database\Query\Processors\Processor->processInsertGetId(Object(Illuminate\Database\Query\Builder), 'insert into `ch...', Array, 'user_id')
#7 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Builder.php(1247): Illuminate\Database\Query\Builder->insertGetId(Array, 'user_id')
#8 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Model.php(684): Illuminate\Database\Eloquent\Builder->__call('insertGetId', Array)
#9 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Model.php(649): Illuminate\Database\Eloquent\Model->insertAndSetId(Object(Illuminate\Database\Eloquent\Builder), Array)
#10 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Model.php(518): Illuminate\Database\Eloquent\Model->performInsert(Object(Illuminate\Database\Eloquent\Builder))
#11 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Builder.php(363): Illuminate\Database\Eloquent\Model->save()
#12 C:\inetpub\wwwroot\vendor\illuminate\support\helpers.php(936): Illuminate\Database\Eloquent\Builder->Illuminate\Database\Eloquent\{closure}(Object(App\Models\UserPreferences))
#13 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Builder.php(364): tap(Object(App\Models\UserPreferences), Object(Closure))
#14 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Model.php(1357): Illuminate\Database\Eloquent\Builder->firstOrCreate(Array)
#15 C:\inetpub\wwwroot\vendor\illuminate\database\Eloquent\Model.php(1369): Illuminate\Database\Eloquent\Model->__call('firstOrCreate', Array)
#16 C:\inetpub\wwwroot\app\Http\Controllers\AccountController.php(58): Illuminate\Database\Eloquent\Model::__callStatic('firstOrCreate', Array)
#17 [internal function]: App\Http\Controllers\AccountController->getPreferences()
#18 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(29): call_user_func_array(Array, Array)
#19 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#20 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#21 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(539): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#22 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#23 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#24 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\AccountController), 'getPreferences', Array)
#25 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#26 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(623): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#27 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#28 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\app\Http\Middleware\Authenticate.php(50): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#31 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#32 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\inetpub\wwwroot\app\Http\Middleware\Maintenance.php(25): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(148): App\Http\Middleware\Maintenance->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(624): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(528): Laravel\Lumen\Application->handleFoundRoute(Array)
#41 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#42 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#43 C:\inetpub\wwwroot\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#44 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#45 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#46 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#47 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#48 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#49 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#50 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#51 C:\inetpub\wwwroot\index.php(26): Laravel\Lumen\Application->run()
#52 {main}`

`[2017-11-14 17:24:09] lumen.ERROR: Intervention\Image\Exception\MissingDependencyException: PHP Fileinfo extension must be installed/enabled to use Intervention Image. in C:\inetpub\wwwroot\vendor\intervention\image\src\Intervention\Image\ImageManager.php:133
Stack trace:
#0 C:\inetpub\wwwroot\vendor\intervention\image\src\Intervention\Image\ImageManager.php(25): Intervention\Image\ImageManager->checkRequirements()
#1 C:\inetpub\wwwroot\vendor\intervention\image\src\Intervention\Image\ImageServiceProviderLumen.php(29): Intervention\Image\ImageManager->__construct(Array)
#2 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(726): Intervention\Image\ImageServiceProviderLumen->Intervention\Image\{closure}(Object(Laravel\Lumen\Application), Array)
#3 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(608): Illuminate\Container\Container->build(Object(Closure))
#4 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(575): Illuminate\Container\Container->resolve('image')
#5 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Application.php(210): Illuminate\Container\Container->make('image')
#6 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(1172): Laravel\Lumen\Application->make('image')
#7 C:\inetpub\wwwroot\vendor\illuminate\support\Facades\Facade.php(159): Illuminate\Container\Container->offsetGet('image')
#8 C:\inetpub\wwwroot\vendor\illuminate\support\Facades\Facade.php(128): Illuminate\Support\Facades\Facade::resolveFacadeInstance('image')
#9 C:\inetpub\wwwroot\vendor\illuminate\support\Facades\Facade.php(215): Illuminate\Support\Facades\Facade::getFacadeRoot()
#10 C:\inetpub\wwwroot\app\Http\Controllers\ImagingController.php(70): Illuminate\Support\Facades\Facade::__callStatic('make', Array)
#11 [internal function]: App\Http\Controllers\ImagingController->getGroupBadge('ADM')
#12 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(29): call_user_func_array(Array, Array)
#13 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(87): Illuminate\Container\BoundMethod::Illuminate\Container\{closure}()
#14 C:\inetpub\wwwroot\vendor\illuminate\container\BoundMethod.php(31): Illuminate\Container\BoundMethod::callBoundMethod(Object(Laravel\Lumen\Application), Array, Object(Closure))
#15 C:\inetpub\wwwroot\vendor\illuminate\container\Container.php(539): Illuminate\Container\BoundMethod::call(Object(Laravel\Lumen\Application), Array, Array, NULL)
#16 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(741): Illuminate\Container\Container->call(Array, Array)
#17 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(707): Laravel\Lumen\Application->callControllerCallable(Array, Array)
#18 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(681): Laravel\Lumen\Application->callLumenController(Object(App\Http\Controllers\ImagingController), 'getGroupBadge', Array)
#19 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(643): Laravel\Lumen\Application->callControllerAction(Array)
#20 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(628): Laravel\Lumen\Application->callActionOnArrayBasedRoute(Array)
#21 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(598): Laravel\Lumen\Application->handleFoundRoute(Array)
#22 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(532): Laravel\Lumen\Application->handleDispatcherResponse(Array)
#23 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#24 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#25 C:\inetpub\wwwroot\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#26 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(148): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#27 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#28 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#29 C:\inetpub\wwwroot\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#30 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(778): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#31 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(534): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#32 C:\inetpub\wwwroot\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(475): Laravel\Lumen\Application->dispatch(NULL)
#33 C:\inetpub\wwwroot\index.php(26): Laravel\Lumen\Application->run()
#34 {main}  `

**Comment by TheOmanNorge** [comment]
Have you had this error message before? Or did you take a new installation and this just came up?

I'm not a guy from Finland, so I had to have Google to help me out on this one

>  That snapshot is already in use. If you are trying to create new avatar, sign up for the Pilvi hotel to your user and create the Ussi avatar settings.

The reason why you might encounter this problem is because I think there is a limit on how many users you can register if they are using the same IP Address. Try go to Table; Users in your database. 

Find your user that you have registered and go to ip_current and remove the IP that is there. 
Try again to register, and see if that fixed your problem. 

I might be 100% wrong about this and is no expert.
But worth a try, if you have not done it!

**Comment by OliverFIN** [comment]
Hi, TheOmanNorge!

Thank you for your time, but this can not be an conflict with IP-address, sadly. This happens randomly with random users trying to register. 1/3 users has this problem (currently in BETA-phase so it's that much). We are not using any proxy at the moment, otherwise it could be because of Cloudflare hiding IP or something.

**Comment by OliverFIN** [comment]
Any suggestions @sant0ro @scottstamp

**Comment by ovflowd** [comment]
Hi @OliverFIN I'm sorry for you having this trouble. All those things will be fixed on official Chocolatey 3.0 release. Thanks!
