### ISSUE TITLE
machine_id empty

### ISSUE THREAD

**Issue by kasperbjerby** [ovflowd/chocolatey#362]
The field "machine_id" in the database is empty.
I would not think that this problem would relate to the CMS but more on the emulator but i guess i was wrong, cause i found [this on arcturus bitbucket].(https://bitbucket.org/Wesley12312/arcturus/issues/797/machineban-didnt-work-on-110)
So could you fix it so  "machine_id" is not empty?

**Comment by iPrinz96** [comment]
I have the same Problem

**Comment by ovflowd** [comment]
I will give a check. But I'm 99% sure that this is an Emulator issue. But anyways, adding code `machine_id` in Chocolatey 3.0 milestone.

**Comment by ovflowd** [comment]
Added on milestone, the bug really exists in Arcturus. So making chocolatey add it.
