### ISSUE TITLE
Client 76%, not emu or SWF

### ISSUE THREAD

**Issue by lifelies** [ovflowd/chocolatey#363]
Hi, back at it again.

I'm getting disconnect on 76% and no, it's not my SWF or my emulator. Tested in on brain and revcms without any problems. 

Went into my lumen error log and there was this and I don't want to edit random files, so I thought lets ask here before. Yes, filled in my .env file correctly. 

`[2017-11-17 14:20:32] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) in C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php:67
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(67): PDO->__construct('mysql:host=loca...', 'arcturus', 'arcturus', Array)
#1 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'arcturus', 'arcturus', Array)
#2 C:\xampp\htdocs\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 C:\xampp\htdocs\vendor\illuminate\database\Connectors\ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(915): call_user_func(Object(Closure))
#6 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(940): Illuminate\Database\Connection->getPdo()
#7 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#8 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#9 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#10 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#11 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#12 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1705): Illuminate\Database\Connection->select('select * from `...', Array, true)
#13 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#14 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(479): Illuminate\Database\Query\Builder->get(Array)
#15 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(463): Illuminate\Database\Eloquent\Builder->getModels(Array)
#16 C:\xampp\htdocs\vendor\illuminate\database\Concerns\BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#17 C:\xampp\htdocs\app\Models\User.php(162): Illuminate\Database\Eloquent\Builder->first()
#18 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(438): App\Models\User->getIsBannedAttribute(NULL)
#19 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('isBanned', NULL)
#20 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('isBanned')
#21 C:\xampp\htdocs\vendor\sofa\hookable\src\Hookable.php(90): Illuminate\Database\Eloquent\Model->getAttribute('isBanned')
#22 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1321): App\Models\User->getAttribute('isBanned')
#23 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(41): Illuminate\Database\Eloquent\Model->__get('isBanned')
#24 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#41 C:\xampp\htdocs\public\index.php(28): Laravel\Lumen\Application->run()
#42 {main}  
[2017-11-17 14:20:32] lumen.ERROR: PDOException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) in C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php:67
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(67): PDO->__construct('mysql:host=loca...', 'arcturus', 'arcturus', Array)
#1 C:\xampp\htdocs\vendor\illuminate\database\Connectors\Connector.php(43): Illuminate\Database\Connectors\Connector->createPdoConnection('mysql:host=loca...', 'arcturus', 'arcturus', Array)
#2 C:\xampp\htdocs\vendor\illuminate\database\Connectors\MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#3 C:\xampp\htdocs\vendor\illuminate\database\Connectors\ConnectionFactory.php(183): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#4 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#5 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(915): call_user_func(Object(Closure))
#6 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(940): Illuminate\Database\Connection->getPdo()
#7 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(399): Illuminate\Database\Connection->getReadPdo()
#8 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(325): Illuminate\Database\Connection->getPdoForSelect(true)
#9 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(657): Illuminate\Database\Connection->Illuminate\Database\{closure}('select * from `...', Array)
#10 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#11 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#12 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1705): Illuminate\Database\Connection->select('select * from `...', Array, true)
#13 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#14 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(479): Illuminate\Database\Query\Builder->get(Array)
#15 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(463): Illuminate\Database\Eloquent\Builder->getModels(Array)
#16 C:\xampp\htdocs\vendor\illuminate\database\Concerns\BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#17 C:\xampp\htdocs\app\Models\User.php(162): Illuminate\Database\Eloquent\Builder->first()
#18 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(438): App\Models\User->getIsBannedAttribute(NULL)
#19 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('isBanned', NULL)
#20 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('isBanned')
#21 C:\xampp\htdocs\vendor\sofa\hookable\src\Hookable.php(90): Illuminate\Database\Eloquent\Model->getAttribute('isBanned')
#22 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1321): App\Models\User->getAttribute('isBanned')
#23 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(41): Illuminate\Database\Eloquent\Model->__get('isBanned')
#24 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#31 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#32 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#33 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#34 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#35 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#36 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#37 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#38 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#39 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#40 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#41 C:\xampp\htdocs\public\index.php(28): Laravel\Lumen\Application->run()
#42 {main}

Next Illuminate\Database\QueryException: SQLSTATE[HY000] [1045] Access denied for user 'arcturus'@'localhost' (using password: YES) (SQL: select * from `bans` where `user_id` = 3 limit 1) in C:\xampp\htdocs\vendor\illuminate\database\Connection.php:664
Stack trace:
#0 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(624): Illuminate\Database\Connection->runQueryCallback('select * from `...', Array, Object(Closure))
#1 C:\xampp\htdocs\vendor\illuminate\database\Connection.php(333): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#2 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1705): Illuminate\Database\Connection->select('select * from `...', Array, true)
#3 C:\xampp\htdocs\vendor\illuminate\database\Query\Builder.php(1690): Illuminate\Database\Query\Builder->runSelect()
#4 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(479): Illuminate\Database\Query\Builder->get(Array)
#5 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Builder.php(463): Illuminate\Database\Eloquent\Builder->getModels(Array)
#6 C:\xampp\htdocs\vendor\illuminate\database\Concerns\BuildsQueries.php(77): Illuminate\Database\Eloquent\Builder->get(Array)
#7 C:\xampp\htdocs\app\Models\User.php(162): Illuminate\Database\Eloquent\Builder->first()
#8 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(438): App\Models\User->getIsBannedAttribute(NULL)
#9 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(340): Illuminate\Database\Eloquent\Model->mutateAttribute('isBanned', NULL)
#10 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Concerns\HasAttributes.php(313): Illuminate\Database\Eloquent\Model->getAttributeValue('isBanned')
#11 C:\xampp\htdocs\vendor\sofa\hookable\src\Hookable.php(90): Illuminate\Database\Eloquent\Model->getAttribute('isBanned')
#12 C:\xampp\htdocs\vendor\illuminate\database\Eloquent\Model.php(1321): App\Models\User->getAttribute('isBanned')
#13 C:\xampp\htdocs\app\Http\Middleware\Authenticate.php(41): Illuminate\Database\Eloquent\Model->__get('isBanned')
#14 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): App\Http\Middleware\Authenticate->handle(Object(Illuminate\Http\Request), Object(Closure))
#15 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#16 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#17 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#18 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#19 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(256): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#20 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(160): Laravel\Lumen\Application->handleFoundRoute(Array)
#21 [internal function]: Laravel\Lumen\Application->Laravel\Lumen\Concerns\{closure}(Object(Illuminate\Http\Request))
#22 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(52): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#23 C:\xampp\htdocs\vendor\rdehnhardt\lumen-maintenance-mode\src\Http\Middleware\MaintenanceModeMiddleware.php(49): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#24 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(149): Rdehnhardt\MaintenanceMode\Http\Middleware\MaintenanceModeMiddleware->handle(Object(Illuminate\Http\Request), Object(Closure))
#25 [internal function]: Illuminate\Pipeline\Pipeline->Illuminate\Pipeline\{closure}(Object(Illuminate\Http\Request))
#26 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Routing\Pipeline.php(32): call_user_func(Object(Closure), Object(Illuminate\Http\Request))
#27 C:\xampp\htdocs\vendor\illuminate\pipeline\Pipeline.php(102): Laravel\Lumen\Routing\Pipeline->Laravel\Lumen\Routing\{closure}(Object(Illuminate\Http\Request))
#28 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(410): Illuminate\Pipeline\Pipeline->then(Object(Closure))
#29 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(166): Laravel\Lumen\Application->sendThroughPipeline(Array, Object(Closure))
#30 C:\xampp\htdocs\vendor\laravel\lumen-framework\src\Concerns\RoutesRequests.php(107): Laravel\Lumen\Application->dispatch(NULL)
#31 C:\xampp\htdocs\public\index.php(28): Laravel\Lumen\Application->run()
#32 {main}  
`

**Comment by ovflowd** [comment]
This error has nothing with the client.

The bug isn't with Chocolatey. You configured something wrong either on Chocolatey configuration or your emulator or your CMS.

**Comment by lifelies** [comment]
So it has nothing to do with this log which shows up every time I try to enter the client? (everytime I try to enter the client this log appears and I can see  that because of the time it is created)

Emulator is working correctly since I tested other CMS's with it and all the swf links etc are working from the chocolatey config file.

**Comment by ovflowd** [comment]
If this appears every time you try to enter in the client. So probably your MySQL configuration is wrong...

**Comment by lifelies** [comment]
Yeh, thought so too, but the only file I configured with the mysql details  is the .env file with the correct details, but this error says: Access denied for user 'arcturus'@'localhost' (using password: YES) since my database isn't named arcturus.

So, basically I have no clue what file of files I need to configure for this too let the client work.

**Comment by TheOmanNorge** [comment]
Your using the database table from Arcturus right? And not plusemulator sql file? 

If you are stuck and not getting anywhere, let me please help you. Is 95% sure you have done a simple mistake. 

I can help you faster, if your up for Teamviewer/Skype and is completely stuck. But this is up too you! 👍 
Not forcing you too anything. Just a way I can help you faster and quicker.

Check your .env file and config.ini file for your emulator. Does it say anything about Arcturus? 😃

**Comment by ovflowd** [comment]
@lifelies you probably didn't configured your `.env` file, and because of that it's saying wrong database details.

**Comment by TheOmanNorge** [comment]
Yes. 
Just a heads up. 

The information that is posted about lumen error log might be old, not updated information. 
If you can register at your Chocolatey CMS, then you know the .env file is correct since It needs access to database in order to create the account. 

Hope you get it working. 👍

**Comment by ovflowd** [comment]
Yes like, @TheOmanNorge said.

**Comment by TheOmanNorge** [comment]
Sorry, deleted it. 
But yes, check out your `.env` file. 

If you know that you can successfully register at your homepage and login then you know for sure it has connection to the database. 

This is whats inside `.env` file by default if not changed.

> DB_CONNECTION=mysql
> DB_HOST=127.0.0.1
> DB_PORT=3306
> DB_DATABASE=arcturus
> DB_USERNAME=arcturus
> DB_PASSWORD=arcturus
> 

As you see, there you have the db and user Arcturus named as in your error log.

**Comment by lifelies** [comment]
Hii, 

I've checked my .env file and everything is filled in correctly and I can also register on my CMS etc. About the lumen error log: The log gets updated everytime I try to enter the client. I would like some teamviewer help. :P I don't have skype though, do you have discord? @TheOmanNorge

**Comment by TheOmanNorge** [comment]
Add me as friend on Discord. 
ID: TheOman#3801

I'll send you a private message.

**Comment by lifelies** [comment]
So, basically he got the same error when he updated to the latest version of chocolatey. I'm wondering if the previous version of chocolatey is available for download? @sant0ro

**Comment by joostply4** [comment]
I've got the same with the 3.000P version. Updated from 3.000L where everything worked fine.
Handshake failed it says, weird because it are the same SWF's and yes I edited everything (instead of /public/swf/... to /swf/...)

**Comment by TheOmanNorge** [comment]
@sant0ro 

I can confirm I have the same problem. I also get the same error as @joostply4 has. 
I've double checked everything. 

I just created a new folder inside public and named the folder public  `"/public/public"` and moved the game folder over there so I didnt need to touch the external_variables and so on.
Example; `http://nightbox.cf/public/game/gamedata/external_variables.txt`

I've also checked the swf settings and they are all correct. 
But this update somehow broke something, I'm not really sure what. 

![handshake fail](https://user-images.githubusercontent.com/15328445/33047289-42231fdc-ce55-11e7-99b4-f830a6c2aa70.png)

This shows up when I try to enter the client, and I get disconnect message. 
`Handshake failed`

I've turned Debug mode on and I got this: 
![disconnectedclient](https://user-images.githubusercontent.com/15328445/33047488-4c5a3c14-ce56-11e7-922a-64753ded3806.png)

EDIT: 
I might have been wrong! I was just in contact with a guy that I helped. 
But he is running the latest Chocolatey CMS and his hotel is running fine. I just visited his hotel. 
I'll update this later today, when I got the swf file and tested them. It might not be a Chocolatey problem after all. But strange why things did get messy for me and someone else even though everything is checked and correct. Let me check and give a report back on this. I'll even post the SWF files later if I'm 100% correct.

I know he is 100% is using the latest version, since I helped him installing it and changing the documentroot. His hotel is live and working. As stated I'll give a report later today when tested myself. 👍 

The hole thing is just strange, since my hotel worked before the update.

**Comment by lifelies** [comment]
@TheOmanNorge I really hope you get it to work. I don't know if this has anything to do with it and if you have the same, but when I try to enter the client and have inspect > network open after hh_human_body there shows loginstep 4 times. I checked other hotels and they got the externals and override's to show up there, which are 4 links. So. maybe it has something to do with it, maybe not.

**Comment by TheOmanNorge** [comment]
I'm headless. I have no clue whats going on. 
Forget what I said. 

I might go and find a older version of Chocolatey I have on my harddisk. 
I'm using a different swf pack, with complete new database. Getting the same error. 😢

**Comment by ovflowd** [comment]
I will give a look on It. For now use an older version.

**Comment by ovflowd** [comment]
Next release a lot thing will be improved and changed. :)

**Comment by ovflowd** [comment]
This will be checked on #258. Thanks for the help!
