### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by DetectedStorm** [ovflowd/chocolatey#366]
When I open the site it shows me what the solution is? 
![- - at - -](https://user-images.githubusercontent.com/33987614/33233577-3ee7b99a-d229-11e7-9c35-a378271fa473.png)

I need help ...

**Comment by TheOmanNorge** [comment]
What OS and webserver is this running on. Windows/Linux? xampp/iis/cpanel? 
Or do you rent a webhotel from a hosting provider? 😸

**Comment by DetectedStorm** [comment]
cpanel

**Comment by TheOmanNorge** [comment]
You have access to WHM or root user?

**Comment by DetectedStorm** [comment]
no

**Comment by DetectedStorm** [comment]
The root user I can access

**Comment by TheOmanNorge** [comment]
If access to root then go to: 
Location: `/var/cpanel/userdata/yourusername`
Select and edit your domain; `documentroot: /home/yourusername/public_html/public `
Rebuild (Run in console) `/scripts/rebuildhttpdconf` and restart Apache. 

Might take some time to take effect, and you might not see the result right away. 

You can also make a subdomain like this; 
That's much faster and not so complicated. 

Example:
![subdom](https://user-images.githubusercontent.com/15328445/33239128-e24f80dc-d29b-11e7-8e92-00ea810a90bd.png)

**Comment by DetectedStorm** [comment]
I do not have what you have
![- - at - -](https://user-images.githubusercontent.com/33987614/33239204-e43004e6-d2ad-11e7-90e3-48a952bd5103.png)

**Comment by TheOmanNorge** [comment]
Eeehhhhh..  
Could you show a picture, of your public_html folder where you have Chocolatey located.. File Manager? 

And there is no way you can change the home directory in Subdomains?

**Comment by DetectedStorm** [comment]
Look
![- - at - -](https://user-images.githubusercontent.com/33987614/33239250-e583c566-d2ae-11e7-83a1-4d6b410e5a71.png)
![- - at - -](https://user-images.githubusercontent.com/33987614/33239251-e7b98b22-d2ae-11e7-8792-5760b59602ab.png)

**Comment by TheOmanNorge** [comment]
Yes somehow you will need to change the documentroot to what I said. 
Try taking contact with your hosting provider. 

I would recommend a VPS or something so you have full control over it.
Cheap hosting providers does not always give you full access to stuff. 

How to use a vps, using console, installing stuff, you must find out yourself (Google is your friend) 
You don't need to use cPanel as there is plenty of fish out in the sea. 

Sorry I could not help you any longer and I wish you good luck! 👍
Of course if you have question related to Chocolatey then I'm happy to answer. 😺

**Comment by DetectedStorm** [comment]
Well thank you for helping. Is there a cheap or free hosting for it?

**Comment by TheOmanNorge** [comment]
Not as I know about. But then again a long time ago I was using a webhosting provider. 
Try go on Google and do some search.  

See if you can find a webhosting company that has.
All the requirements in order to run Chocolatey. 
Change of Documentroot and also access to SSH/Terminal

If you find someone who can, then you are not far off to get it working.

**Comment by DetectedStorm** [comment]
Well no problem and thank you again for help <3
