### ISSUE TITLE
I have a problem

### ISSUE THREAD

**Issue by slikkerbr** [ovflowd/chocolatey#367]
When I open the site it shows me what the solution is?

![gag](https://user-images.githubusercontent.com/34293145/33642928-627a8ae8-da23-11e7-8929-32980fc5b93a.png)

I am using a VPS and Apache xampp

help me please

**Comment by TheOmanNorge** [comment]
Went on Google, took me 1 min to find. 
https://www.youtube.com/watch?v=-xrPXUc6-rc

Change the documentroot to public folder of Chocolatey cms. 👍 
htdocs/public.

**Comment by ovflowd** [comment]
@slikkerbr are you still having this issue?

**Comment by ovflowd** [comment]
Closed, no new feedback from the author.
