### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by talhayetkin** [ovflowd/chocolatey#369]
Can anyone help me with this error ? [http://prntscr.com/hlhxna](url)

**Comment by TheOmanNorge** [comment]
You might be missing the vendor files. 
If you download the binaries branch you will get the vendor folder. 

Go to your php.ini and find this:
` allow_url_fopen & allow_url_include  ` and set those values to On

Still not work? Might be because composer is not installed or migrated yet.

**Comment by talhayetkin** [comment]
@TheOmanNorge I dont have the Vendor files when i downloaded the binaries ?

**Comment by TheOmanNorge** [comment]
You will find it here 😃 :
https://github.com/sant0ro/chocolatey

Image: 
![vendor_download](https://user-images.githubusercontent.com/15328445/33803875-4365cc06-dd9a-11e7-9c00-0ddcc158e031.png)

**Comment by Playsaray** [comment]
@TheOmanNorge Must o set de Vendor map in Public Map ?

**Comment by Playsaray** [comment]
@TheOmanNorge Where must i set the vendor map ?

**Comment by TheOmanNorge** [comment]
In your rootfolder, where you have placed the content of Chocolatey in. 
wwwroot

**Comment by talhayetkin** [comment]
@TheOmanNorge I get this error now: http://prntscr.com/hli2go . I gave me full permission.

**Comment by TheOmanNorge** [comment]
See my post here. 
I explain how to fix! 😃 

Click on it.
#368

**Comment by TheOmanNorge** [comment]
Updated 368 on how to install Composer and migrating. 
Included images, if you don't understand.

**Comment by TheOmanNorge** [comment]
Got it working or still having troubles? 😸

**Comment by talhayetkin** [comment]
@TheOmanNorge [http://prntscr.com/hlqjh9](url) . My client is white and i got blocked plug ins?

**Comment by TheOmanNorge** [comment]
Yes, check and see if Adobe Flash Player is blocked.

Could you post your swf settings you have in your Chocolatey.php file?
If not, make sure they are correct.

**Comment by talhayetkin** [comment]
@TheOmanNorge [http://prntscr.com/hlqtf1](url)

**Comment by TheOmanNorge** [comment]
SWF settings is wrong. 
Since the new update, is not completely the same as last time. 

Remove /public from the links

Correct links: 

```
Gordon: http://harbohotel.eu/swf/gordon/PRODUCTION-201611291003-338511768
Flash: http://harbohotel.eu/swf/gordon/PRODUCTION-201611291003-338511768/Habbo.swf
External Variables: http://harbohotel.eu/swf/gamedata/external_variables.txt
Figuredata: http://harbohotel.eu/swf/gamedata/figuredata.xml
Furnidata:  http://harbohotel.eu/swf/gamedata/furnidata.xml
Productdata: http://harbohotel.eu/swf/gamedata/productdata.txt
External Flash Text: http://harbohotel.eu/swf/gamedata/external_flash_texts.txt
External Override Variables: http://harbohotel.eu/swf/gamedata/override/external_override_variables.txt
External Overrride Texts: http://harbohotel.eu/swf/gamedata/override/external_flash_override_texts.txt
```

**Comment by talhayetkin** [comment]
@TheOmanNorge Thanks for all the support but [http://prntscr.com/hlr8fw](url)

**Comment by TheOmanNorge** [comment]
Check and see if your using the right Habbo.swf file.
If that is not the problem try open up developer tools and look for errors when entering the Client.

If you see files missing, then try to fix that. 👨

**Comment by TheOmanNorge** [comment]
In developer tools.
```
action = [log], label = [debug], value = [Load event IO ERROR for file "hh_human_body.swf"]
habboapi.min.js:1 action = [log], label = [warn], value = [IO Error, send or load operation failed for file "hh_human_body.swf"]
habboapi.min.js:1 action = [log], label = [error], value = [Can't log login error: [object Object]]
habboapi.min.js:1 action = [log], label = [fatal], value = [Can't log login crash: [object Object]]
```
Tries to load in these files, but failing. 

> http://harbohotel.eu/swf/gordon/hh_human_body.swf
> http://harbohotel.eu/swf/gordon/hh_human_item.swf

Not saying this is fixing your problem. (Since I don't know myself) but if there a way to fix this. Try fixing it and see if you still get error messages. 

Might be located in external_variables/external_override_variables somewhere.

**Comment by talhayetkin** [comment]
@TheOmanNorge Nope, http://harbohotel.eu/swf/gordon/hh_human_body.swf
http://harbohotel.eu/swf/gordon/hh_human_item.swf are in my swf map :(

**Comment by ovflowd** [comment]
Hi @Playsaray can you test another SWF pack, your hh_human_body seems to be corrupted.

Happy new year 😄
