### ISSUE TITLE
users table not updated by Chocolatey ? Can't login to Arcturus

### ISSUE THREAD

**Issue by Pumpk1in** [ovflowd/chocolatey#370]
Hi !

I have a problem with the login on Arcturus : disconnected at 76%
After looking at things I could have missed, I pretty sure that the users table is not updated by chocolatey.

1. AUTH_TICKET is never filled in DB. Maybe that's why I'm disconnected.
2. I saw that the password stored in the users table after the register process is not the same as the one in chocolatey_users_id. (so you can't update your email on your profile, because it will say wrong password as it checks the one in users table and not the one in chocolatey_users_id)
3. I also saw that the username in the users table is not updated. But I'm sure I changed it during the register process.

So, what could be the problem with the users table not updated by chocolatey ? :/

Thanks !

**Comment by ovflowd** [comment]
I don't know what's happening here. I will investigate when I start again to code Chocolatey.

It's scheduled for the new changes of milestone 3 being started on day **12/20/2017**.

**Comment by ovflowd** [comment]
Added it to roadmap #258 thanks for reporting the bug!
