### ISSUE TITLE
Discconnection 

### ISSUE THREAD

**Issue by OG4KUSH** [ovflowd/chocolatey#372]
Hello i keep gettin disconnected im using a swf pack not from retroripper.com(websitedown) but from somewhere else it supposed to be r63b so idk if it works with this one its for the plus emu also the ports are correct using port 3000 and ip for emu and cms side 127.0.0.1 so it should be working,,

and it looks like this https://gyazo.com/15ff9830e484b8e7e497b0dc65074405

`Chocolatey
index.php:1 Cross-origin plugin content from  must have a visible size larger than 400 x 300 pixels, or it will be blocked. Invisible content is always blocked.
habboapi.min.js:1 action = [clientload], label = [starting], value = [Initalizing Habbo Client.]
habboapi.min.js:1 action = [clientload], label = [web.view.start], value = [undefined]
habboapi.min.js:1 action = [clientload], label = [client.init.start], value = [undefined]
habboapi.min.js:1 action = [clientload], label = [client.init.swf.loaded], value = [undefined]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 0/62005]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 4096/62005]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 12288/62005]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 28672/62005]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 32768/62005]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_body.swf"  bytes: 62005/62005]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 0/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 4096/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 12288/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 28672/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 32768/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 65536/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 98304/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 131072/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 163840/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 196608/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 229376/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 262144/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 294912/349781]
2habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 327680/349781]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event PROGRESS for file "hh_human_item.swf"  bytes: 349781/349781]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event INIT for file "hh_human_item.swf"]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event STATUS 200 for file "hh_human_item.swf"]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event COMPLETE for file "hh_human_item.swf"]
habboapi.min.js:1 action = [log], label = [debug], value = [Analyzing library "hh_human_item", content is not a MovieClip]
habboapi.min.js:1 action = [log], label = [debug], value = [	Bytes loaded: 349781/349781]
habboapi.min.js:1 action = [log], label = [debug], value = [Preparing library "hh_human_item"]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event INIT for file "hh_human_body.swf"]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event STATUS 200 for file "hh_human_body.swf"]
habboapi.min.js:1 action = [log], label = [debug], value = [Load event COMPLETE for file "hh_human_body.swf"]
habboapi.min.js:1 action = [log], label = [debug], value = [Analyzing library "hh_human_body", content is not a MovieClip]
habboapi.min.js:1 action = [log], label = [debug], value = [	Bytes loaded: 62005/62005]
habboapi.min.js:1 action = [log], label = [debug], value = [Preparing library "hh_human_body"]
habboapi.min.js:1 action = [clientload], label = [client.init.core.init], value = [undefined]
habboapi.min.js:1 action = [clientload], label = [client.init.socket.ok], value = [0]
habboapi.min.js:1 action = [clientload], label = [client.init.handshake.start], value = [undefined]
habboapi.min.js:1 action = [clientload], label = [client.init.handshake.fail], value = [undefined]
habboapi.min.js:1 action = [performance], label = [averageFramerate], value = [14]`

**Comment by TheOmanNorge** [comment]
I see the that you get 
> client.init.handshake.fail


And this might be because of the latest version of Chocolatey that you're using. 
Santoro is working on a fix for the issue, but there is no ETA on when it's fixed or when exectly a new version will be released. 

But for now, try using this version instead:
https://github.com/sant0ro/chocolatey/releases/tag/3.000N

**Comment by ovflowd** [comment]
Exactly like @TheOmanNorge said, just use https://github.com/sant0ro/chocolatey/releases/tag/3.000N this version.
