### ISSUE TITLE
Disconnected when joining hotel

### ISSUE THREAD

**Issue by SamOtten** [ovflowd/chocolatey#374]
I get a disconnected message when joining my hotel. The emulator is on and on the same port as the chocolatey.conf.

This is my browser console:
> action = [clientload], label = [starting], value = [Initalizing Habbo Client.]
> habboapi.min.js:1:5685
> action = [clientload], label = [web.view.start], value = [undefined]
> habboapi.min.js:1:5685
> action = [log], label = [error], value = [Can't log login error: [object Object]]
> habboapi.min.js:1:5685
> action = [log], label = [fatal], value = [Can't log login crash: [object Object]]

Hope you guys can help.

**Comment by ovflowd** [comment]
Please use this version.: https://github.com/sant0ro/chocolatey/releases/tag/3.000N

Latest version isn't ready.
