### ISSUE TITLE
Login-Email visible for other users.

### ISSUE THREAD

**Issue by ghost** [ovflowd/chocolatey#375]
When you go to https://YOURHOTELURL/api/public/users?name=USERNAME

Their email is visible.

Please fix this.

Thx.

**Comment by ovflowd** [comment]
Really? But in Habbo isn't the same?

**Comment by ovflowd** [comment]
Oh true, https://www.habbo.com.br/api/public/users?name=sant0ros, in Habbo isn't public. Added to milestone.
