### ISSUE TITLE
Plesk Error

### ISSUE THREAD

**Issue by iPrinz96** [ovflowd/chocolatey#380]
Hello,
i will update the Chocolatey Version.

I have edit the wwwroot to /public.
And than come a blank site.

Here my PHP Error log:

`[Sun Jan 07 00:17:17.501726 2018] [ssl:warn] [pid 11004:tid 140388023036032] AH01909: RSA certificate configured for dev.RetroHotel.xx:443 does NOT include an ID which matches the server name
[Sun Jan 07 13:54:57.344936 2018] [proxy_fcgi:error] [pid 15443:tid 140387502987008] [client ip.xxx.xxx.xxx:57664] AH01071: Got error 'PHP message: PHP Fatal error:  Uncaught Error: Call to a member function buildField() on null in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/index.php:190\nStack trace:\n#0 {main}\n  thrown in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/index.php on line 190\n'
[Sun Jan 07 14:03:39.805838 2018] [ssl:warn] [pid 11004:tid 140388023036032] AH01909: RSA certificate configured for dev.RetroHotel.xx:443 does NOT include an ID which matches the server name
[Sun Jan 07 14:05:03.909557 2018] [proxy_fcgi:error] [pid 15891:tid 140387649844992] [client ip.xxx.xxx.xxx:33648] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:06:33.934350 2018] [proxy_fcgi:error] [pid 16038:tid 140387544946432] [client ip.xxx.xxx.xxx:42416] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:06:35.575044 2018] [proxy_fcgi:error] [pid 16038:tid 140387534456576] [client ip.xxx.xxx.xxx:42600] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:06:36.768123 2018] [proxy_fcgi:error] [pid 16038:tid 140387513476864] [client ip.xxx.xxx.xxx:42690] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:06:45.681276 2018] [proxy_fcgi:error] [pid 16038:tid 140387492497152] [client ip.xxx.xxx.xxx:43554] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:07:20.687706 2018] [proxy_fcgi:error] [pid 16038:tid 140387555436288] [client ip.xxx.xxx.xxx:47096] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:07:21.354008 2018] [proxy_fcgi:error] [pid 16038:tid 140387544946432] [client ip.xxx.xxx.xxx:47136] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:07:21.898635 2018] [proxy_fcgi:error] [pid 15891:tid 140387618375424] [client ip.xxx.xxx.xxx:47180] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:07:39.543110 2018] [ssl:warn] [pid 11004:tid 140388023036032] AH01909: RSA certificate configured for dev.RetroHotel.xx:443 does NOT include an ID which matches the server name
[Sun Jan 07 14:07:40.117468 2018] [fcgid:warn] [pid 16425:tid 140387649844992] [client ip.xxx.xxx.xxx:48694] mod_fcgid: stderr: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4
[Sun Jan 07 14:07:40.117564 2018] [fcgid:warn] [pid 16425:tid 140387649844992] [client ip.xxx.xxx.xxx:48694] mod_fcgid: stderr: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4
[Sun Jan 07 14:08:33.559531 2018] [ssl:warn] [pid 11004:tid 140388023036032] AH01909: RSA certificate configured for dev.RetroHotel.xx:443 does NOT include an ID which matches the server name
[Sun Jan 07 14:08:37.292089 2018] [proxy_fcgi:error] [pid 16790:tid 140387482007296] [client ip.xxx.xxx.xxx:54668] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:08:38.254134 2018] [proxy_fcgi:error] [pid 16816:tid 140387639355136] [client ip.xxx.xxx.xxx:54766] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.1/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:08:56.675773 2018] [ssl:warn] [pid 11004:tid 140388023036032] AH01909: RSA certificate configured for dev.RetroHotel.xx:443 does NOT include an ID which matches the server name
[Sun Jan 07 14:20:43.688993 2018] [proxy_fcgi:error] [pid 17304:tid 140387639355136] [client ip.xxx.xxx.xxx:42802] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:27:25.180747 2018] [proxy_fcgi:error] [pid 17304:tid 140387419068160] [client ip.xxx.xxx.xxx:54476] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:28:17.963170 2018] [proxy_fcgi:error] [pid 17304:tid 140387544946432] [client ip.xxx.xxx.xxx:59798] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:28:18.652179 2018] [proxy_fcgi:error] [pid 17140:tid 140387502987008] [client ip.xxx.xxx.xxx:59864] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
[Sun Jan 07 14:28:35.280653 2018] [proxy_fcgi:error] [pid 17156:tid 140387492497152] [client ip.xxx.xxx.xxx:33294] AH01071: Got error 'PHP message: PHP Warning:  require_once(/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php): failed to open stream: No such file or directory in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\nPHP message: PHP Fatal error:  require_once(): Failed opening required '/var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/../vendor/autoload.php' (include_path='.:/opt/plesk/php/7.0/share/pear') in /var/www/vhosts/RetroHotel.xx/dev.RetroHotel.xx/bootstrap/app.php on line 4\n'
`

**Comment by TheOmanNorge** [comment]
Do you have the vendor folder? 
![vendor](https://user-images.githubusercontent.com/15328445/34650662-12c4bb2a-f3c5-11e7-876b-fc7960865c92.png)

**Comment by iPrinz96** [comment]
That was this Problem.
But i have a new Problem.
I cant Join the Hotel...

This link is Only for developer^^ 
http://dev.habboriginal.de/

**Comment by ovflowd** [comment]
Hi @iPrinz96 don't use last Chocolatey version `3.0P` it's an unstable and under development version.

I'm going to remove it. Switch back to Chocolatey `3.0N`.

All those 3.0XX versions are under development versions, so the last "stable" development version of Chocolatey 3.0 it's 3.0N, they aren't real releases, just changes that I made public for newbie people.

The real Chocolatey 3.0 version will be released next month.

**Comment by iPrinz96** [comment]
Oh. Okay.
I wait of the new Stable Version.
Good luck :)
