### ISSUE TITLE
Public folder error

### ISSUE THREAD

**Issue by Hyvion** [ovflowd/chocolatey#381]
I was trying to modify the logo and some images in the **"public"** folder, but it just does not work, no matter how many changes I made, the only thing that changed was the favicon. Can anybody help me? **I use xampp.** 
- I'm sorry for my English I'm Spanish :s

**Comment by iPrinz96** [comment]
U must change you apache settings to from: c:/xampp/htdocs to c:/xampp/htdocs/public

**Comment by TheOmanNorge** [comment]
For now, I recommend using a different version of Chocolatey. 
The latest version is broken, and Santoro is working on a fix for the problem. 
If your using the latest version then you will need to change documentroot. 

On Xampp.
- Go to your xampp folder, where you have it installed. 
- Go here: \apache\conf\httpd.conf 
Open up httpd.conf and you will be able to change documentroot there. 
It has to be change to what iPrinz96 is saying. 😃 

This is the one I recommend you using for now until a new version has been released.
https://github.com/sant0ro/chocolatey/releases/tag/3.000N

If you want to modify the logo you will need to do a few steps. 
The logo can be found here: `public/habbo-web/assets/images/sprite.png`
Width &  Height can be changed here: `public/habbo-web/app.css`

Or you can simply just make a new image and just change a few lines in `app.css` 
Search for `.header__habbo__logo`

If you have trouble, please let us know.

**Comment by Hyvion** [comment]
Thank you very much, everything works perfectly now  :) 👍
