### ISSUE TITLE
error in composer.lock

### ISSUE THREAD

**Issue by Ravoit** [ovflowd/chocolatey#382]
D:\Development\xampp\htdocs\habbo> composer create-project sant0ro/chocolatey
Installing sant0ro/chocolatey (2500)
  - Installing sant0ro/chocolatey (2500): Downloading (100%)
Created project in D:\Development\xampp\htdocs\habbo\chocolatey

  [Seld\JsonLint\ParsingException]
  "./composer.lock" does not contain valid JSON
  Parse error on line 1:
  git {    "_readme":
  ^
  Expected one of: 'STRING', 'NUMBER', 'NULL', 'TRUE', 'FALSE', '{', '['

create-project [-s|--stability STABILITY] [--prefer-source] [--prefer-dist] [--repository REPOSITORY] [--repository-url REPOSITORY-URL] [--dev] [--no-dev] [--no-custom-installers] [--no-scripts] [--no-progress] [--no-secure-http] [--keep-vcs] [--no-install] [--ignore-platform-reqs] [--] [<package>] [<directory>] [<version>]

**Comment by ovflowd** [comment]
That's weird. The other way you can install Cocolatey it's a direct pull from this repository, or just downloading a zip from the `binaries` branch.

Maybe the Packagist it's outdated, I will give a check.

**Comment by fgpons** [comment]
*Sorry for my spelling, I'm Spanish*

The same problem happens to me.
Any solution?
Do you have any solution to the problem?

the "binaries" does not work

**Comment by ovflowd** [comment]
Hey just a really quick tip. Just delete the `composer.lock` file and after that execute again `composer install`.
