### ISSUE TITLE
Error CMS!

### ISSUE THREAD

**Issue by fgpons** [ovflowd/chocolatey#385]
_Sorry for my spelling, I'm Spanish_

The problem really worries me, because the holo does not work.

cmd: http://prntscr.com/ifv5ox
localhost: http://prntscr.com/ifv7le

I have PHP 7.1.13
Composer 1.6.3 (the last)
windows7, xampp

any solution?

**Comment by ovflowd** [comment]
Hey just delete your `composer.lock` and type composer install again.

**Comment by fgpons** [comment]
It doesn't work
https://prnt.sc/iiyver

**Comment by ovflowd** [comment]
Just ignore the "bash post-install.sh" thing. It worked successfully.

**Comment by fakuch1** [comment]
the same error occurs! https://prnt.sc/ifv7le

**Comment by fgpons** [comment]
Solved!
but the register does not work 
http://prntscr.com/ijaubx
http://prntscr.com/ijawpl

**Comment by ovflowd** [comment]
@fakuch1 I recommend you read all the documentation on our wiki. You need configure the Google ReCaptcha in order to the captcha work.

**Comment by ovflowd** [comment]
Observation.: You put the ReCaptcha key in the wrong place. You putted it in the Adsene place.

**Comment by fakuch1** [comment]
I'm sorry, then I put it right ..
http://prntscr.com/ijc3us

but still it does not work, what could it be?

**Comment by fgpons** [comment]
Solved, I had to delete the database and execute the "php artisan migrate" command again.

**Comment by ovflowd** [comment]
Great that you solved it!
