### ISSUE TITLE
Emulator

### ISSUE THREAD

**Issue by fgpons** [ovflowd/chocolatey#390]
_Sorry for my spelling, I'm Spanish._

I want to translate the emulator, is there any way to do it?
I want to edit the welcome logo and some commands.

http://oi63.tinypic.com/efm78x.jpg

**Comment by ovflowd** [comment]
@fakuch1 this is the repository about Chocolatey. Not HabboLatino or any other emulator. I'm sorry.

I recommend you creating a help thread at RaGEZONE. I would be amazed helping you at RaGEZONE. Just tag my username.

Cheers!
