### ISSUE TITLE
Register error after moving to SSL

### ISSUE THREAD

**Issue by Zensoe** [ovflowd/chocolatey#397]
Hello

So, after I moved to SSL along with sucuri, it is no longer possible for people to register on my website.
I've tried to remove SSL and run pure HTTP, and that works. (I discovered this, because my "test" website on HTTP, was still allowing people to register). The funny thing is, that if I delete MY or anyone else's account that WAS registered on my HTTP test site(Same DB, moved it), they can actually register again?

I've attached a few pictures of the issue.

(And yeah, I did re-register a new recaptcha and retrieved a new key on googles site. Unfortunately google does not allow links starting with https:// to be associated with the recaptcha. Only link.com is available)

![1](https://user-images.githubusercontent.com/38543543/39021782-a32fca02-4432-11e8-9a78-f91cd483e9ef.png)
![2](https://user-images.githubusercontent.com/38543543/39021783-a34db210-4432-11e8-82ad-978899ab35ef.png)

**Comment by ovflowd** [comment]
Ah the `MethodNotAllowed` exception it's because you just opened the `/new` uri in a new tab. Keep in mind that that will not work, since `/new` can only by requested by a form.

I would recommend you do the following.

Clear the log files, `storage/logs/lumen.log`. Try to register again, and attach here the generated content in the `storage/logs/lumen.log` file.

Cheers.

**Comment by Zensoe** [comment]
I cleared everything in the log folder, buuuut I'm really struggling to generate some new errors in it.
No errors show up, it's all empty.

**Comment by Zensoe** [comment]
[lumen.log](https://github.com/ovflowd/chocolatey/files/1930062/lumen.log)


I removed the stupid dsdasda typo mistake. Still not working though.

**Comment by ovflowd** [comment]
The only error that appears here it's the 'dfgdfg'. 
Could you follow this: https://github.com/ovflowd/chocolatey/blob/master/SUPPORT.md ?

Thanks!

**Comment by Zensoe** [comment]
**Inform a complete message of your problem, and what's happening:**
Users cannot register on the website. They receive the following two errors:
"User is already registered" and "Please confirm the you are a human", even though the DB is completely fresh.

**Attach your lumen.log if it exists:**
The lumen.log contains no errors unfortunately.

**Attach images of the reported bugs/glitches:**
![1](https://user-images.githubusercontent.com/38543543/39053966-aebc0c5e-44b0-11e8-8fb7-2e00573cf6ae.png)
![2](https://user-images.githubusercontent.com/38543543/39053967-aedb5d84-44b0-11e8-8383-72ddb1afacea.png)
Pictures attached.

**Attach also Information about Operational System, Web Server, PHP Versiom, and other infos:**
**OS:** Windows Server 2016 Standard
**Web server:** IIS version 10
**PHP version:** 7.1.14 (x86)
**MySQL version:** 5.5
**RAM:** 16 GB
**Firewall:** Sucuri
**Running SSL.**

**HAR file:**
Attached. Please note that SSL was disabled during this, however it's not working with or without SSL.
When it fails HAR for other people not registered before:
[bobba.rip.har.zip](https://github.com/ovflowd/chocolatey/files/1932332/bobba.rip.har.zip)

When it goes through for people registered before:
[bobba.success.har.zip](https://github.com/ovflowd/chocolatey/files/1932481/bobba.success.har.zip)



**Explain what you tried and how tried:**
Tried with and without SSL activated.
Re-importing a fresh database, redoing "php artisan migrate"
Reached out to host and asked if google recaptcha IP's was blocked. (Host is not maintaining any blacklists)
Reached out to Sucuri and asked if google recaptcha could be blocked somewhere. (All google services allowed)
Obtained a new Recaptcha KEY.
--- I do feel that something might be blocked by the firewall, as it's working on my test server with no external firewall. Can it be the internal firewall? lol

**Comment by ovflowd** [comment]
Hey @Zensoe the error that is happening isn't a server error. Chocolatey is saying that you actually have an account with this e-mail address.

There isn't a bug in Chocolatey. Could you check the table `chocolatey_users_id` (I think this is the name). If there is already an e-mail like yours?

**Comment by Zensoe** [comment]
No there is not. I’ve tried every random letter combination available haha. It’s falsely showing this error unfortunately.

**Comment by ovflowd** [comment]
That's weird. Totally weird.

Have you tried another password? I will give a check here. Can you send your server uri?

**Comment by Zensoe** [comment]
Https://bobba.rip
Or do you mean serv access?

**Comment by ovflowd** [comment]
Nope, just the uri 😃

**Comment by ovflowd** [comment]
Oh, I think I know what could be. Try writing a smaller e-mail.

As far I know Arcturus has an e-mail size limit.

**Comment by ovflowd** [comment]
![image](https://user-images.githubusercontent.com/12037269/39069731-12393b3e-44b7-11e8-91ab-0afed0cfec51.png)

I registered with success.

**Comment by Zensoe** [comment]
How did you maange to do that?

I’ve just tried with tea@hotmail.con on a random WiFi, and I received the error. WTF

**Comment by ovflowd** [comment]
Could you just try using anonymous window? I think Chocolatey blocked your IP.

You can deactivate the max users by IP. (I think if your IP is already registered you cannot register again.)

**Comment by ovflowd** [comment]
![image](https://user-images.githubusercontent.com/12037269/39069950-e3d51366-44b7-11e8-902e-635681cffe77.png)

Everything Ok here. And I loved your modifications 💖

**Comment by Zensoe** [comment]
Thanks buddy 😄 Where and how do I modify that? I’ve been searching for such feature. I’ve editted the “max avatars” to 5, but can it be that one?

**Comment by ovflowd** [comment]
I think max avatars is the amount of avatars each account can have. Isn't that. Let me check where it could be the IP limiter.

**Comment by ovflowd** [comment]
Just remove this if: https://github.com/ovflowd/chocolatey/blob/master/app/Http/Controllers/LoginController.php#L79

**Comment by Zensoe** [comment]
Thanks. I’m on the phone ATM. I’ll return with a response as soon as I get home :) I appreciate the support man!

**Comment by ovflowd** [comment]
You're welcome. 😃

**Comment by Zensoe** [comment]
Removing the IF statement solved the issue.

Thanks bud :D

**Comment by ovflowd** [comment]
Thanks! I'm glad it solved.

Closing the Issue.
