### ISSUE TITLE
Registration Error and PHP error

### ISSUE THREAD

**Issue by Skila0** [ovflowd/chocolatey#404]
So im having a registration error. Whenever i try to register and  do the captcha, it says you need to verify that your not a bot even though i done it correctly and another red popup comes up saying "oops there is something wrong, you can try again in a few moments". 
habbo-web-news/en/production/front.html:1 Failed to load resource: the server responded with a status of 500 ()
2api/public/registration/new:1 Failed to load resource: the server responded with a status of 500 ()
----
Other error is when on the cmd trying to execute php artisan migrate
comes up with error saying access denied to arcturus @ localhost etc.

**Comment by TheOmanNorge** [comment]
The reason for the access denied; is because there is something wrong with the database details. 

Check your .env file and make sure your MySQL details is correct.

**Comment by ovflowd** [comment]
Exactly like @TheOmanNorge said 😄

**Comment by Skila0** [comment]
Thanks alot @TheOmanNorge fixed everything dude

**Comment by ovflowd** [comment]
Amazing!
